import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:firebase_core/firebase_core.dart'; // 1. ADD THIS IMPORT
import 'package:shared_preferences/shared_preferences.dart';
import 'firebase_options.dart'; // 2. ADD THIS IMPORT (Generated by CLI)
import 'screens/tabs/home.dart';
import 'splash_screen.dart'; // Ensure path is correct (removed starting /)

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  // 3. INITIALIZE FIREBASE (This is the fix!)
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Show status bar but hide navigation gestures
  SystemChrome.setEnabledSystemUIMode(
    SystemUiMode.manual,
    overlays: [SystemUiOverlay.top], // only status bar
  );

  final prefs = await SharedPreferences.getInstance();
  final bool seenOnboarding = prefs.getBool('seenOnboarding') ?? false;

  runApp(MyApp(seenOnboarding: seenOnboarding));
}

class MyApp extends StatelessWidget {
  final bool seenOnboarding;
  const MyApp({super.key, required this.seenOnboarding});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'HearingHands',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        primarySwatch: Colors.green,
        scaffoldBackgroundColor: Colors.white,
      ),
      home: seenOnboarding ? const Home() : const SplashScreen(),
    );
  }
}
